---
- name: Deploy Tomcat in MicroShift cluster
  hosts: localhost
  vars:
    project: "hello-tomcat"
  tasks:

    - name: Create ~/.kube
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0700'

    - name: Copy kubeconfig
      ansible.builtin.copy:
        src: kubeconfig
        dest: ~/.kube/config
        mode: '0644'

- name: Create Project
  hosts: localhost
  vars_files:
    - variables.yml
  roles:
    - gmagnotta.ocp.project

- name: Deploy application
  hosts: localhost
  vars_files:
    - variables.yml
  tasks:

    - name: Deploy resources
      kubernetes.core.k8s:
        namespace: "{{ project }}"
        definition: "{{ lookup('kubernetes.core.kustomize', dir='files/k8s/overlays/prod/') }}"
      register: oc_apply_result